
spring:
    application:
        name: gateway
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    redis:
        database: 13
        host: 192.168.3.2
        port: 6379
        sysName: manange
        password: redis123456
        pool:
          #连接池支持的最大连接数
          max-active: 600
          #连接池中连接用完时,新的请求等待时间,毫秒
          max-wait: 10000
          #连接池中最多可空闲maxIdle个连接
          max-idle: 300
server:
    port: 8762 #启动端口
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      min-response-size: 2048

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
security:
  user:
    name: user
    password: ${REGISTRY_SERVER_PASSWORD:password}
management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
#zuul:
#  max:
#    host:
#      connections: 5000
#  host:
#    socket-timeout-millis: 60000
#    connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

#请求和响应GZIP压缩支持
feign:
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
info:
  name: 网关服务
  desc: 网关服务是所有接口的主入口
zuul:
  sensitive-headers: Cookie,Set-Cookie

